openapi: 3.0.3
info:
  description: This the description of mugimugi API (https://doujinshi.org)
  version: 0.1.0
  title: Mugimugi
  contact:
    email: jeanmarc.moly@gmail.com
servers:
  - url: https://www.doujinshi.org/api
paths:
  /:
    get:
      requestBody:
        content:
          application/xml:
            schema:
              oneOf:
                - $ref: "#/components/schemas/Cat"
                - $ref: "#/components/schemas/Dog"
      responses:
