name: Python package

on:
  workflow_run:
    workflows: ["Format"]
    types:
      - completed

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: pipenv
        run: pip install pipenv
      - name: check code
        run: pipenv run check
      - name: test code
        run: pipenv run test

  package:
    needs: validate
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2@
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2@
        with:
          python-version: ${{ matrix.python-version }}
      - name: pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: pipenv install --deploy
